name: run_sync
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0 # Downgraded for compatibility with firebase_data_connect
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  firebase_data_connect: ^0.1.2+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.1.0

flutter:
  uses-material-design: true