// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB85mUeOkFYJWgeNGSwdLDBVs_wXyGA9Eg',
    appId: '1:955190789987:web:3bc2f1479c57193697f556',
    messagingSenderId: '955190789987',
    projectId: 'run-sync-942bb',
    authDomain: 'run-sync-942bb.firebaseapp.com',
    storageBucket: 'run-sync-942bb.firebasestorage.app',
    measurementId: 'G-BK727LSM3P',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBxfCyXALGMjj9B_bVhWZ1L_b7XW-4Rlc',
    appId: '1:955190789987:ios:1a2ee159e73cf15c97f556',
    messagingSenderId: '955190789987',
    projectId: 'run-sync-942bb',
    storageBucket: 'run-sync-942bb.firebasestorage.app',
    iosBundleId: 'com.example.runSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBxfCyXALGMjj9B_bVhWZ1L_b7XW-4Rlc',
    appId: '1:955190789987:ios:1a2ee159e73cf15c97f556',
    messagingSenderId: '955190789987',
    projectId: 'run-sync-942bb',
    storageBucket: 'run-sync-942bb.firebasestorage.app',
    iosBundleId: 'com.example.runSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB85mUeOkFYJWgeNGSwdLDBVs_wXyGA9Eg',
    appId: '1:955190789987:web:49752d70d4144d1b97f556',
    messagingSenderId: '955190789987',
    projectId: 'run-sync-942bb',
    authDomain: 'run-sync-942bb.firebaseapp.com',
    storageBucket: 'run-sync-942bb.firebasestorage.app',
    measurementId: 'G-4LJP1W81WP',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: "AIzaSyAgZ2lk6zdq59cHOwtiTf8IivNi-b-M93M",
    appId: "1:955190789987:web:fc683da10ea976f597f556",
    projectId: "run-sync-942bb",
    authDomain: "run-sync-942bb.firebaseapp.com",
    storageBucket: "run-sync-942bb.firebasestorage.app",
    messagingSenderId: "955190789987",
    measurementId: "G-7FLWXGXSWP"

  );
}